export const CfgNames = {
horses: [
  "Iron Comet",
  "Midnight Echo",
  "Stormglass",
  "Ash Runner",
  "Silver Wake",
  "Black Meridian",
  "Red Lantern",
  "Quiet Thunder",
  "Last Signal",
  "Cold Horizon",
  "Foxglove King",
  "Grave Dancer",
  "Starless Night",
  "Copper Wind",
  "Old Compass",
  "Broken Oath",
  "Winter Bell",
  "Dust & Glory",
  "Grey Undertow",
  "Hollow Crown",
  "Fallow Light",
  "Northbound",
  "Kindled Ash",
  "Sea of Nails",
  "Long Memory",
  "Pale Harbour",
  "Crosswind",
  "Blackwater Run",
  "Signal Fire",
  "Dead Reckoning",
  "Burnished Steel",
  "Low Horizon",
  "Amber Tide",
  "Whispering Vale",
  "Salt Road",
  "Cold Iron King",
  "Moon over Slate",
  "Cinder Track",
  "Broken Latitude",
  "Night Ferry",
  "Brass Lantern",
  "Hard Weather",
  "Stillwater Pact",
  "Gravel Choir",
  "White Signal",
  "Ember Wake",
  "Old North Star",
  "Stonebound",
  "Half Remembered",
  "Distant Smoke",
  "Ironleaf",
  "Tide Caller",
  "Grey Compass",
  "Last Embers",
  "Black Gull",
  "Farthing Wind",
  "Frost Meridian",
  "Hearthless",
  "Signal Loss",
  "Low Country",
  "Weathered King",
  "Sable March",
  "Quiet Reign",
  "Cold Signal",
  "Bitter Wake",
  "Ash & Salt",
  "Starboard Light",
  "Broken Sound",
  "Long Drift",
  "Grim Horizon",
  "Nightbound",
  "Candle Smoke",
  "Iron Psalm",
  "Old Harbour",
  "Fading Bell",
  "Stone Lantern",
  "Last Crossing",
  "Windfall Crown",
  "Dead Calm",
  "Rusted Banner",
  "Far Watch",
  "Winter Signal",
  "Gravel Wind",
  "Low Tide King",
  "Hollow Wake",
  "Crossing Ash",
  "Black Snow",
  "Old Weather",
  "Silver Moor",
  "Storm Ledger",
  "Cold Reach",
  "Quiet Anchor",
  "Iron Drift",
  "Northfall",
  "Shadow Buoy",
  "Drowned Bell",
  "Hard Compass",
  "Night Jar",
  "White Ash King",
  "Broken Sextant",
  "Tallow Wind",
  "Last Buoy",
  "Grey Standard",
  "Ember Compass",
  "Still Signal",
  "Stormwarden",
  "Cold Wake",
  "Iron Tide",
  "Low Ember",
  "Far Meridian",
  "Salt Crown",
  "Black Shore",
  "Fallow Crown",
  "Windlass",
  "Quiet Crossing",
  "Ash Horizon",
  "Dead Light",
  "Northward Bell",
  "Longshore King",
  "Cinder Wake",
  "Moonless Watch",
  "Iron Lowlands",
  "Broken Flag",
  "Stormbound",
  "Cold Beacon",
  "Gravel Tide",
  "Last Horizon",
  "Weather Signal",
  "Pale Runner",
  "Old Signalman",
  "Ash Banner",
  "Silent Undertow",
  "Windburn",
  "Blackfield",
  "Saltbound",
  "Iron Harbour",
  "Stillwind",
  "Low Crown",
  "Night Compass",
  "Distant Bell",
  "Cold Gallant",
  "Grave Horizon",
  "Windward Ash",
  "Last Iron",
  "Grey Crossing",
  "Tide of Cinders",
  "Broken North",
  "Quiet Standard",
  "Storm Ashore",
  "White Undertow",
  "Low Signal",
  "Fading Wake",
  "Iron Memory",
  "Saltwind King",
  "Cold Ledger",
  "Black Tern",
  "Ashbound",
  "North Signal"
],
  trainers: [
    "Hawthorne Stables",
    "Redgate Racing",
    "Northmoor Yard",
    "Black Fen Lodge",
    "Ironbridge Bloodstock",
    "Ravenhill Training",
    "Westreach Stud",
    "Kingswell Yard"
  ],

  tracks: [
    "Stonebridge",
    "Raven Downs",
    "Whitebarrow",
    "Ashford Heath",
    "Northwatch Park",
    "Blackmere",
    "Kingsfall",
    "Red Hollow"
  ]
};
