
export const config = {
    "sea_messages" : [
        "The sea is calm. Nothing terrible has happened yet.",
        "The tide is doing something… suspicious.",
        "Someone swears they saw bubbles spelling a warning.",
        "The sea remains calm. This is probably a lie.",
        "The water looks normal. Too normal.",
        "A wave lingers longer than it should.",
        "The sea makes a noise it did not need to make.",
        "The tide comes in fast, like it knows what it’s doing.",
        "There’s a rhythmic splashing that feels… deliberate.",
        "The water briefly adopts a deeply inappropriate shape.",
        "A shape rises from the sea, looks round, and sinks again.",
        "The tide pulls back with a cheeky little wiggle.",
        "A nearby buoy is bobbing far too enthusiastically.",
        "The sea is behaving in a way best described as ‘weird’.",
        "A wave refuses to crash. Make of that what you will.",
        "The water is… moist. Unhelpfully so.",
        "Nobody asked the sea to do *that*.",
        "The tide arrives early and leaves everyone disappointed.",
        "Something slaps the shoreline with intent.",
        "A foam pattern forms that spells disaster. Literally."
    ],
    "sea_change": { "colors": [
        { h: 191, s: 87, l: 47, a: 1 }, // tropical (too nice)
        { h: 219, s: 77, l: 48, a: 1 }, // normal blue
        { h: 224, s: 58, l: 46, a: 1 }, // deep Atlantic
        { h: 231, s: 86, l: 28, a: 1 }, // deep blue
        { h: 173, s: 90, l: 42, a: 1 }, // greeny blue
        { h: 200, s: 47, l: 37, a: 1 }  // steel grey
    ], "speed" : 0.00005 }, // lerp per ms - bigger = faster
    "weather_messages": [
        "The weather is fine. This will not last.",
        "A cloud passes overhead. With purpose.",
        "The wind adjusts itself, just to see if you notice.",
        "Rain considers happening, then decides against it.",
        "The air feels heavy, like it’s thinking.",
        "A gust of wind takes something personally.",
        "The sky adopts a colour it shouldn’t be allowed to have.",
        "It is technically dry, but only just.",
        "The breeze smells faintly of regret.",
        "The sun appears briefly, as a joke.",
        "A distant rumble suggests the weather is warming up.",
        "The clouds gather, then remember they have elsewhere to go.",
        "The wind comes from a direction you were not expecting.",
        "The air pressure drops in a way that feels pointed.",
        "A light drizzle begins, stops, and watches you.",
        "The sky darkens slightly, for no reason it will explain.",
        "The weather is doing that thing again.",
        "A sudden warmth is followed by immediate disappointment.",
        "The atmosphere feels unsettled. Emotionally.",
        "The horizon looks threatening, but only on a technicality.",
        "Something moves in the clouds that isn’t part of the plan."
    ],
    "fish_messages": [
        "The nets come up heavy. No one says with what.",
        "A trawler reports a full haul and a quiet crew.",
        "The catch exceeds expectations. So does the smell.",
        "Something moves in the net after it’s been emptied.",
        "The pots are disturbed, but not opened.",
        "A winch strains longer than it should.",
        "The nets tear in a place that makes no sense.",
        "A boat returns early without filing a report.",
        "The haul is within quota. The crew is not reassured.",
        "Something is caught that does not fit the mesh.",
        "A fisherman refuses to explain what he just saw.",
        "A trawler’s log skips a page.",
        "A fish looks at you with its full complement of eyes.",
        "The nets come back arranged... differently.",
        "The pots are heavier today. No extra catch is recorded.",
        "A winch operator refuses to use that net again.",
        "The echo sounder shows something briefly, then apologises.",
        "The catch is sorted quickly, with no discussion.",
        "A deckhand washes his hands longer than necessary.",
        "The nets are clean. This is not an improvement.",
        "Something hits the hull from underneath, once.",
        "A trawler drifts for a while before remembering to move.",
        "A line is cast from shore and immediately retrieved.",
        "Someone hooks something and quietly cuts the line.",
        "The bait is taken. The hook is returned.",
        "A fisherman claims the fish was watching him.",
        "A mackerel re-died. Twice.",
        "A man swears he saw a ghost crab. What does that even mean?",
        "The pots come up empty, but not unused.",
        "A net is repaired without being examined.",
        "The skipper marks the location, then scratches it out.",
        "The catch requires more ice than planned.",
        "Something is thrown back without being logged.",
        "A gull refuses to approach the offal.",
        "The hold smells wrong for the species caught.",
        "A trawler changes course for no recorded reason.",
        "The nets are cut free rather than hauled.",
        "A catch is landed at night and sold without comment.",
        "The fish are smaller than expected. The heads are not.",
        "A deckhand counts the haul twice and stops halfway.",
        "The sounder shows depth where there should be none.",
        "A pot line hums under tension, then goes slack.",
        "The nets are warm when hauled.",
        "The crew agrees not to fish that ground again.",
        "A fisherman vomits, then asks for a cigarette.",
        "The bycatch is unusually tidy.",
        "A trawler idles while everyone waits for something.",
        "The nets come up tangled with themselves.",
        "A catch is dumped before reaching harbour.",
        "Someone sharpens a knife they don’t use.",
        "The hold is sealed longer than regulations require.",
        "A fish breaks itself trying to get out.",
        "The pots are moved overnight by someone else.",
        "A trawler radios in, then decides not to.",
        "The nets smell of copper and old water.",
        "A fisherman refuses to fish alone anymore.",
        "The catch is blessed, unofficially.",
        "The sounder briefly shows the seabed moving.",
        "A trawler avoids a patch of calm water.",
        "The nets come back lighter, but harder to haul.",
        "A fish is caught with something already inside it.",
        "The crew eats in silence tonight.",
        "The bait is gone. The hooks are bent straight.",
        "A fisherman swears the fish knew his name.",
        "The pots are stacked facing away from the sea.",
        "The nets are retired without discussion.",
        "A haul is landed and immediately buried in ice.",
        "The trawler sells nothing from that trip.",
        "Someone crosses themselves before hauling.",
        "The fish are counted. One is counted twice.",
        "A fisherman says the tide felt wrong today.",
        "The nets come back humming softly.",
        "A catch is recorded under ‘miscellaneous’.",
        "The crew agrees the fish were not from here.",
        "A line snaps without being under tension.",
        "The fish stop moving all at once.",
        "A trawler leaves harbour later than planned.",
        "The pots are hauled carefully, like glass.",
        "A fisherman swears the sea gave it back."
],
    "land_messages": [
        "A field gate swings shut behind you.",
        "Something moves in the hedgerow and decides not to.",
        "A hand-painted sign has been corrected, aggressively.",
        "A tractor idles with no one in it.",
        "You pass the same milestone twice.",
        "A dog watches you until you are no longer visible.",
        "The road surface changes without explanation.",
        "A footpath sign points somewhere you don’t remember going.",
        "Someone waves from a distance, then stops.",
        "A hedge has been cut back in a hurry.",
        "You hear footsteps that do not belong to you.",
        "A field is empty in a way that feels organised.",
        "The wind moves through the grass against its own direction.",
        "A farm track has fresh tyre marks and no destination.",
        "A radio plays faintly from somewhere it shouldn’t.",
        "A gate is open that was definitely closed before.",
        "You smell smoke, but see no fire.",
        "A crow lands nearby, waits, and leaves.",
        "A lane narrows slightly more than it used to.",
        "Someone has stacked stones where no one stacks stones.",
        "A handwritten notice has been removed, leaving the nails.",
        "The land feels temporarily occupied."
    ],
    "people_messages": [
        "An old man looks you over and nods once.",
        "An elderly woman pauses her shopping to watch you pass.",
        "A child stares at you without curiosity.",
        "A man leans on a gate and does not move.",
        "An old lady smiles and asks if you’re lost.",
        "A boy stops kicking his ball until you’re gone.",
        "A woman corrects your pronunciation carefully.",
        "A man asks if you’re visiting or staying.",
        "An old fisherman tells you it’s quieter now.",
        "A girl whispers something and is hushed.",
        "A farmer watches you from the field edge.",
        "An elderly couple stop talking when you approach.",
        "A child asks if you live here.",
        "A man points out a shorter route you weren’t taking.",
        "An old woman asks how long you’ll be around.",
        "A teenager looks at you, then at the road behind you.",
        "A shopkeeper asks who sent you.",
        "An old man laughs and says, ‘You’ll see.’",
        "A woman reminds you to shut the gate.",
        "A boy asks if you’re ‘with them’.",
        "An elderly woman tells you the weather’s wrong today.",
        "A man steps aside to let you pass, watching closely.",
        "A child waves, then lowers their hand.",
        "A woman says you just missed it.",
        "An old farmer tells you not to go that way.",
        "A man asks if you’ve checked the tides.",
        "An old lady asks if you’ve spoken to anyone yet.",
        "A teenager offers help, then withdraws it.",
        "A man glances at your map and says nothing.",
        "An elderly man says it’s better in summer.",
        "A woman tells you people will notice.",
        "A boy runs off to fetch someone.",
        "An old woman thanks you for understanding.",
        "A man asks where you heard about this place.",
        "An elderly couple watch you until you turn the corner.",
        "A woman reminds you to mind the dogs.",
        "A man says you’re early.",
        "An old lady says you’re late.",
        "A teenager asks if you’re supposed to be here.",
        "A shopkeeper asks what you’re looking for.",
        "An old fisherman asks if you’ve been warned.",
        "A child asks if you can see it too.",
        "A man suggests you take the upper road.",
        "An elderly woman says it’s quieter than it was.",
        "A boy asks if you’re lost on purpose.",
        "A woman glances behind you, then smiles.",
        "An old man says it used to be busier.",
        "A teenager watches you like it’s their job.",
        "A man tells you the road’s not what it was.",
        "An old lady asks if you know the rules.",
        "A child points at you and stops.",
        "A woman says you’ve got the wrong shoes.",
        "An elderly man nods approvingly, reluctantly.",
        "A boy asks if you’re staying long.",
        "A farmer tells you the land remembers.",
        "A woman says you’ll get used to it.",
        "An old man asks what you’ve heard.",
        "A child asks if you’re afraid.",
        "A man says not many people come this way now.",
        "An elderly woman warns you about the lower path.",
        "A teenager says you stand out.",
        "A shopkeeper watches you leave.",
        "An old fisherman tells you not to ask questions.",
        "A boy asks if you’re one of them.",
        "A woman tells you not to touch anything.",
        "An old man says you’ll do.",
        "A man glances at the sky and frowns.",
        "An elderly woman says you missed something important.",
        "A teenager asks if you’re leaving soon.",
        "A woman says people talk.",
        "An old man watches until you’re out of sight.",
        "A man asks if you’re staying forever.",
        "A man says it’s best not to linger.",
        "An elderly couple nod in unison.",
        "A woman tells you it’s safer during the day.",
        "A boy looks relieved when you pass.",
        "An old fisherman says you’ll understand later.",
        "A man asks who you’re meeting.",
        "An elderly woman says you seem polite.",
        "A teenager tells you not to worry.",
        "A child waves again; with all of its hands.",
        "An old man says you’ve been noticed.",
        "A woman says you should’ve got here earlier.",
        "A farmer asks if you’ve been told.",
        "An elderly lady smiles like it’s decided.",
        "A man says, ‘Right then,’ and walks away."
    ]
}